- name: stop eyepi capture service
  systemd:
    name: eyepi-capture.service
    daemon_reload: yes
    state: stopped
    enabled: yes
    masked: no
  ignore_errors: yes

- name: download go-eyepi binary
  get_url:
    url: "https://github.com/borevitzlab/go-eyepi/releases/download/{{version}}/go-eyepi"
    dest: /usr/bin/go-eyepi
    mode: 0755

- name: create go-eyepi config directory
  file:
    dest: /etc/eyepi
    state: directory

- name: template out eyepi.conf
  template:
    src: eyepi.conf.j2
    dest: /etc/eyepi/eyepi.conf

- name: copy go-eyepi systemd service file
  copy:
    src: eyepi-capture.service
    dest: /etc/systemd/system/eyepi-capture.service

- name: enable eyepi capture service
  systemd:
    name: eyepi-capture.service
    daemon_reload: yes
    state: restarted
    enabled: yes
    masked: no
