- include: libgphoto2.yml

- set_fact:
    gphoto2_src: "{{source_dir}}/gphoto2-{{version or 'latest'}}"
    gphoto2_build: "{{build_dir}}/gphoto2"
  no_log: yes

- file:
    state: absent
    path: "{{gphoto2_build}}/"
  no_log: yes

- name: Download gphoto2
  git:
    repo: https://github.com/gphoto/gphoto2.git
    clone: yes
    force: yes
    update: yes
    version: "{{version or 'HEAD'}}"
    dest: "{{gphoto2_src}}"

- file:
    path: "{{gphoto2_build}}"
    state: directory
  no_log: yes

- name: Copy gphoto2 to build dir
  command: "rsync -a {{gphoto2_src}}/ {{gphoto2_build}}"
  no_log: yes

# # for some reason this just doesnt work :(
# - name: configure gphoto2
#   shell: autoreconf --install --symlink && ./configure --prefix /usr
#   args:
#     chdir: "{{gphoto2_build}}"
#
# - name: Make gphoto2
#   make:
#     chdir: "{{gphoto2_build}}"
#     params:
#       NUM_THREADS: "{{ansible_processor_cores}}"
#
# - name: Install gphoto2
#   make:
#     chdir: "{{gphoto2_build}}"
#     target: install
#     creates: "/usr/local/bin/gphoto2"

- name: Build gphoto2
  shell: >
    cd "{{gphoto2_build}}" &&
    autoreconf --install --symlink &&
    ./configure --prefix /usr &&
    make -j2 &&
    make install
  args:
    creates: "/usr/local/bin/gphoto2"
  no_log: yes
