- name: Add sftp.traitcapture.org to global known hosts
  lineinfile:
    create: yes
    state: present
    line: "sftp.traitcapture.org,130.56.244.172 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMPadBuXC+ewb6a4j/fej04jQQzsXN7M8XOMugSUIc1Z4m2DNcMLzZileNWVkwzebLBTEvx7oQ6UFh2XVwG56Cc="
    regexp: "^.*sftp.traitcapture.org.*"
    dest: /etc/ssh/ssh_known_hosts

- file:
    path: /etc/ssh/ssh_known_hosts
    state: file
    mode: 0755
    owner: root

- name: Add sftp.traitcapture.org to known hosts for root (just to be safe)
  lineinfile:
    create: yes
    state: present
    line: "sftp.traitcapture.org,130.56.244.172 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMPadBuXC+ewb6a4j/fej04jQQzsXN7M8XOMugSUIc1Z4m2DNcMLzZileNWVkwzebLBTEvx7oQ6UFh2XVwG56Cc="
    regexp: "^.*sftp.traitcapture.org.*"
    dest: /root/.ssh/known_hosts

- file:
    path: /root/.ssh
    owner: root
    state: directory
    mode: 0700

- name: Get a new ssh key from the server.
  uri:
    url: "https://traitcapture.org/api/v3/remote/by-machine/{{ansible_machine_id}}?token={{api_key}}"
    method: POST
    body: "hostname={{inventory_hostname}}&token={{api_key}}"
    return_content: yes
  register: sshkey
  when: api_key is defined

- copy:
    content: "{{(sshkey.content|from_json)['id_rsa']}}"
    dest: /root/.ssh/id_rsa
    mode: 0600
  when: sshkey.content is defined and sshkey.content|from_json is defined

- copy:
    content: "{{(sshkey.content|from_json)['id_rsa.pub']}}"
    dest: /root/.ssh/id_rsa.pub
  when: sshkey.content is defined and sshkey.content|from_json is defined
