- name: stop telegraf
  service:
    name: telegraf
    state: stopped
    daemon_reload: yes
  ignore_errors: yes

- name: copy rainmeter program
  copy:
    src: rain-sensor
    dest: /usr/local/bin/rain-sensor
    mode: 0755

- name: "Update telegraf config."
  blockinfile:
    path: /etc/telegraf/telegraf.conf
    marker: "# {mark} RAINMETER ANSIBLE MANAGED BLOCK"
    block: |
      # Read metrics from rain sensor
      [[inputs.exec]]
        commands = [
          "/usr/local/bin/rain-sensor -pin {{ pin }}"
        ]
        timeout = "30s"
        data_format = "influx"

- name: restart telegraf service
  service:
    name: telegraf
    state: restarted
    enabled: yes
    daemon_reload: yes
