- include_role:
    name: common
    tasks_from: pkgbuild.yml
  vars:
    tarball: aur-136b82a621a7d1e63562e09c3b2bb30f4dd8eae8

- name: create lsyncd config directory
  file:
    path: /etc/lsyncd/
    state: directory

- name: lsyncd configuration file
  copy:
    src: lsyncd.conf.lua
    dest: /etc/lsyncd/lsyncd.conf.lua

# if you dont do this lsyncd will spank you.
- name: stop any lsyncd service running
  systemd:
    name: lsyncd.service
    daemon_reload: yes
    state: stopped
  ignore_errors: yes

- name: lsyncd service
  copy:
    src: lsyncd.service
    dest: /usr/lib/systemd/system/lsyncd.service

- name: enable lsyncd
  systemd:
    name: lsyncd.service
    daemon_reload: yes
    state: restarted
    enabled: yes
    masked: no
