- name: Get cpu serialnumber
  shell: grep -Eor "Serial.*([[:xdigit:]])" /proc/cpuinfo | cut -d " " -f2
  register: check_serial
  check_mode: no
  ignore_errors: yes
  no_log: yes
  changed_when: True

- set_fact:
    inventory_cpuserial: "{{check_serial.stdout}}"

- debug: msg="{{ansible_machine_id}}:{{inventory_cpuserial}} using name {{inventory_hostname}}"

- name: Set hostname
  hostname: name="{{inventory_hostname}}"

- name: Set /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: Generate locales
  locale_gen:
      name: "{{item}}"
  with_items:
    - en_AU.UTF-8

- name: Set locale
  command: localectl set-locale LANG=en_AU.UTF-8
  no_log: yes

- name: Timezone Australia/Canberra
  timezone: name=Australia/Canberra

- name: Install Sudo
  pacman:
    update_cache: yes
    name: sudo
    state: present
  no_log: yes

- name: Passwordless Sudo
  lineinfile:
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    regexp: "^%wheel"
    state: present
    dest: /etc/sudoers
    validate: "visudo -cf %s"

- name: Disable root logins
  file:
    dest: /root/.ssh/authorized_keys
    state: absent

- name: Passwordless Sudo
  lineinfile:
    line: "{{item.line}}"
    regexp: "{{item.regexp}}"
    state: present
    dest: /etc/ssh/sshd_config
  with_items:
    - {line: "PasswordAuthentication no", regexp: "^.*PasswordAuthentication .*"}
    - {line: "PermitRootLogin prohibit-password", regexp: "^.*PermitRootLogin .*"}

- name: vm.overcommit_memory fix
  sysctl:
    name: vm.overcommit_memory
    state: present
    value: 1
    sysctl_set: yes

- name: create source_dir
  file:
    path: "{{source_dir}}"
    state: directory

- name: create build_dir
  file:
    path: "{{build_dir}}"
    state: directory

- name: reboot service upload
  copy:
    src: "reboot_schedule.service"
    dest: "/etc/systemd/system/reboot_schedule.service"

- name: reboot timer template
  template:
    src: "reboot_schedule.timer.j2"
    dest: "/etc/systemd/system/reboot_schedule.timer"

- name: enable/start the timer
  systemd:
    name: eyepi-capture.service
    daemon_reload: yes
    enabled: yes
    masked: no
