- set_fact:
    i2c_modules:
      - i2c-dev
      - i2c-bcm2708

- name: "modprobe {{ item }}"
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ i2c_modules }}"

- name: add lines to modules.load.d/i2c.conf to autoload modules
  lineinfile:
    line: "{{ item }}"
    create: yes
    path: /etc/modules-load.d/i2c.conf
  with_items: "{{ i2c_modules }}"

