# force is probably not a good idea, however we should be fine in this case
- name: Install {{suite}} packages
  pacman:
    name: "{{ pkgs }}"
    state: present
    force: yes
    update_cache: yes
