- name: include vault
  include_vars: vault.yml
  no_log: true
  tags: always

- name: include user list
  include_vars: userlist.yml
  no_log: true
  tags: always

- include_tasks: base_setup.yml
  tags: base,setup,always

- include_tasks: rpi_config.yml
  tags: base,setup

- include_tasks: users.yml
  tags: base,users

- include_tasks: updatepkgs.yml
  tags: base,pkgs

- include_tasks: installpkgs.yml suite="Base" pkgs="{{packages_base}}"
  tags: base,pkgs

- include_tasks: installpkgs.yml suite="Dist" pkgs="{{pacman_pkgs}}"
  tags: base,pkgs,dist

- include_tasks: i2csetup.yml
  tags: base,i2c,sensors

- include_tasks: telegraf.yml
  tags: telegraf,metrics
