# install telegraf thru aur
- include_tasks: aur.yml pkg_name="telegraf-bin"

- name: template config out
  template:
    src: templates/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf

- name: restart telegraf service
  service:
    name: telegraf
    state: restarted
    enabled: yes
    daemon_reload: yes
